### ISSUE TITLE
Error with user lookup field

### ISSUE THREAD

**Issue by Marcosfau** [carfup/PCFControls#44]
Hi Clement,

Thanks for your prompt reply in discussion.

Regarding to the issue, we had installed the solution that last modified on 24 Jul and encountered below error when saving value to  user lookup field. We have couple of user lookup fields in the quick edit form and all meet the same error.
The lookup relationship is between a new custom entity and user entity. 

Besides, I found a post that may be related to the error. Thanks.
https://yaweriqbal.com/2019/10/28/web-api-an-error-occurred-while-validating-input-parameters/

"An error occurred during the update.

An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property '{field name}' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean propertyWithValue)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithoutValue(IODataJsonLightReaderResourceState resourceState, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)"

**Comment by carfup** [comment]
Thanks a lot for your feedback here, it was indeed a major issue.
And i'm glad to tell you that it's fixed with the version published now : #45 

https://github.com/carfup/PCFControls/releases/tag/1.3.2.1

Enjoy !

**Comment by Marcosfau** [comment]
Great job, thanks for the quick response. 

Will try and let you know if fixed the issue.

**Comment by Marcosfau** [comment]
Thanks Clement. 

The latest release solved my issue. Legend.
