### ISSUE TITLE
Decimals not supported error

### ISSUE THREAD

**Issue by jjint** [carfup/PCFControls#51]
Hi,

Getting an issue when saving decimals using the quick edit form.
I have installed the latest version PCF Controls 1.3.2.1
We had raised a similar issue before ( https://github.com/carfup/PCFControls/issues/20) but it does not seem to be fixed.
Could you please help?

An error occurred during the update.

An error occurred while validating input parameters: Microsoft.OData.ODataException: Cannot convert a value to target type 'Edm.Decimal' because of conflict between input format string/number and parameter 'IEEE754Compatible' false/true.
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideResourceValue, String propertyName, Nullable`1 isDynamicProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryDataProperty(IODataJsonLightReaderResourceState resourceState, IEdmProperty edmProperty, String propertyTypeName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean isDeltaResourceSet)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.<ReadResourceContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.StartReadingResource()
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceSetItemStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)
   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)
   at Microsoft.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)
   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)
   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)

Thanks

**Comment by carfup** [comment]
Hello,
As mentioned in the #20 , it will be included in the next release.
I keep you updated on that !
Regards

**Comment by carfup** [comment]
The fix is now pushed to the release branch : #53

**Comment by maverickandgoose83** [comment]
thanks @carfup , any idea on when you plan to do a new release? prefer to use your managed solution that re-building ourselves

**Comment by carfup** [comment]
@maverickandgoose83 I'm digging into an other improvement : handling multi-columns.
If I'm able to integrate this "easily", I will try to integrate this along with the decimal fix.
The complicated part with the deployment of PCF controls is that it requires a solution upgrade every time this is why I'm trying to push new releases with several fixes/improvements at the same time.

Let's say that latest within the next 2 weeks, the new release will be out.

**Comment by carfup** [comment]
You will find the link to the latest version here : https://github.com/carfup/PCFControls/releases/tag/1.3.3.0

Clément
